feat: support aztec v4 dockerless cli (#2)

diff --git a/gaztec-install b/gaztec-install
--- a/gaztec-install
+++ b/gaztec-install
@@ -1,41 +1,54 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-install_aztec() {
-  local version=$1
-
-  local aztec_path="$HOME/.aztec/v$version/bin"
-
-  if [[ ! -f "$aztec_path/aztec" ]]; then
-    echo "Installing aztec $version in $aztec_path"
-    VERSION=$version BIN_PATH=$aztec_path NON_INTERACTIVE=1 bash -i <(curl -s https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/tags/v$version/aztec-up/bin/aztec-install)
-  fi
-}
 
 AZTEC_VERSION=""
-# go from the current dir to the root of the filesystem and find the first .gaztecrc file
+# go from the current dir to the root of the filesystem and find the first .aztecrc or .gaztecrc file
 dir=$(pwd)
 while [[ $dir != "/" ]]; do
-  if [[ -f "$dir/.gaztecrc" ]]; then
-    AZTEC_VERSION=$(cat $dir/.gaztecrc | tr -d '\n')
-    echo "Using aztec version $AZTEC_VERSION from $dir/.gaztecrc"
+  # fail if both .aztecrc and .gaztecrc files are found
+  if [[ -f "$dir/.aztecrc" && -f "$dir/.gaztecrc" ]]; then
+    echo "Found both .aztecrc and .gaztecrc files in $dir. Please only use one of them." >&2
+    exit 1
+  fi
+
+  if [[ -f "$dir/.aztecrc" ]]; then
+    AZTEC_VERSION=$(cat $dir/.aztecrc | tr -d '\n')
+    echo "Using aztec version $AZTEC_VERSION from $dir/.aztecrc" >&2
     break
   fi
+
+  if [[ -f "$dir/.gaztecrc" ]]; then
+    AZTEC_VERSION=$(cat $dir/.gaztecrc | tr -d '\n')
+    echo "Using aztec version $AZTEC_VERSION from $dir/.gaztecrc" >&2
+    # deprecation warning
+    echo "WARNING: .gaztecrc is deprecated. Please rename to .aztecrc instead." >&2
+    break
+  fi
+
   dir=$(dirname $dir)
 done
 
 # fallback
 if [[ -z "$AZTEC_VERSION" ]]; then
-  echo "No .gaztecrc file found in the current or parent directories starting from $(pwd). Falling back to the latest version."
+  echo "No .aztecrc file found in the current or parent directories starting from $(pwd). Falling back to the latest version." >&2
   # fetch the latest version from github releases, remove the v prefix
   AZTEC_VERSION=$(curl -s https://api.github.com/repos/AztecProtocol/aztec-packages/releases/latest | jq -r '.tag_name' | sed 's/^v//')
-  echo "Latest version is $AZTEC_VERSION"
+  echo "Latest version is $AZTEC_VERSION" >&2
 fi
 
-export VERSION=$AZTEC_VERSION
+AZTEC_PATH="$HOME/.aztec"
+AZTEC_UP="$AZTEC_PATH/bin/aztec-up"
 
-install_aztec $AZTEC_VERSION
+if [[ ! -f "$AZTEC_UP" ]]; then
+  echo "aztec-up could not be found. Installing it..." >&2
+  # FOUNDRY_DIR is needed due to a bug in aztec-up
+  FOUNDRY_DIR="$HOME/.foundry" VERSION=$AZTEC_VERSION NON_INTERACTIVE=1 bash -i <(curl -sL https://install.aztec.network/$AZTEC_VERSION)
+fi
 
-AZTEC="$HOME/.aztec/v$AZTEC_VERSION/bin/aztec"
-AZTEC_NARGO="$HOME/.aztec/v$AZTEC_VERSION/bin/aztec-nargo"
-AZTEC_POSTPROCESS_CONTRACT="$HOME/.aztec/v$AZTEC_VERSION/bin/aztec-postprocess-contract"
+if ! $AZTEC_UP list | grep $AZTEC_VERSION; then
+  echo "Installing aztec version $AZTEC_VERSION..." >&2
+  $AZTEC_UP install $AZTEC_VERSION
+fi
+
+AZTEC="$AZTEC_PATH/versions/$AZTEC_VERSION/node_modules/.bin/aztec"
